# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run: 
          name: Install monaca
          command: sudo npm install -g monaca # install monaca
      - run: 
          name: Install Onsen UI
          command: npm install onsenui --save # install onsen ui
#      - run:
#          name: create dummy project for cordova
#          command: cp -r .cordova /home/circleci/.cordova
      - run: 
          name: Install node modules
          command: npm install # install npm packages
#      - run:
#          name: Update Monaca
#          command: monaca update --force 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # try build
      - run: 
          name: Build Project
          command: monaca transpile
      - run:
          name: Copy transpiled file to Heroku
          command: |
            git clone https://heroku:$HEROKU_API_KEY@git.heroku.com/islander-jeju-app.git islander-jeju-app && cp -rv ~/repo/www/* ./islander-jeju-app/
      - run:
          name: Commit files into Heroku git
          command: cd islander-jeju-app && git config --global user.email "yo1226@gmail.com" && git config --global user.name "Yoseob Kim" && git add * && git commit -am "deploy"
      - run:
          name: Push files into Heroku git and Deploy
          command: cd islander-jeju-app && ls -al && git push https://heroku:$HEROKU_API_KEY@git.heroku.com/islander-jeju-app.git master
